name: Release Charts

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Create Helm release artifacts
        run: |
          helm package ./helm-charts/falcon-sensor

      - name: Release artifacts to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./falcon*.tar.tgz
          allowUpdates: true
          name: Release ${{ github.ref }}
          token: ${{ secrets.CR_TOKEN }

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
