name: Release Helm Charts

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Create Helm release artifacts
        run: |
          helm package ./helm-charts/falcon-sensor

      - name: Release artifacts to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./falcon*.tgz
          allowUpdates: true
          name: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update index.yaml
        run: |
          git fetch origin gh-pages
          git reset --hard HEAD
          git checkout gh-pages
          helm repo index . --url https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }} --merge index.yaml
          git add index.yaml
          git commit -m "Update index.yaml to latest Helm release"
          git push origin gh-pages
